platform:
#  - x64
  - x86

install:
  - MSBuild.exe pyauto.sln /target:Build /property:Configuration=Release,Platform=x64
  - choco install doxygen.install -y
  - python makefile.py

build: off
test: off
deploy: off
